In [1]:
import category_encoders as ce
import pandas as pd
import numpy as np

In [2]:
propiedadesTrain = pd.read_csv('train.csv')
propiedadesTest = pd.read_csv('test.csv')
featuresTrain = pd.read_csv('featuresTrain3.csv')
featuresTest = pd.read_csv('featuresTest3.csv')

# Este notebook lo voy a usar para hacer un one hot de las variables categoricas:

In [3]:
#variables a encodear
categorias = ['provincia']

In [4]:
#featuresTrain sin lavariable encodeada:
featuresTrain.head()

,id,ciudad,provincia,antiguedad,habitaciones,garages,banos,metroscubiertos,metrostotales,idzona,...,precio,anio,mes,dia,datoBienCargado,peso_IDF_descripcion,peso_IDF_titulo,metrosdescubiertos,tipodepropiedad_cb,caracteristicas_cb
0,254099,Benito Juárez,Distrito Federal,2.210044,2.0,1.0,2.0,4.394449,4.394449,23533.0,...,2273000.0,2015.0,8.0,23.0,1,0.086408,0.000000,0.000000,0.478679,0.390827
1,53461,La Magdalena Contreras,Distrito Federal,2.397895,3.0,2.0,2.0,5.594711,5.198497,24514.0,...,3600000.0,2013.0,6.0,28.0,0,0.344349,0.165371,0.000000,0.386072,0.475439
2,247984,Tonalá,Jalisco,1.791759,3.0,2.0,2.0,4.976734,5.117994,48551.0,...,1200000.0,2015.0,10.0,17.0,1,0.992218,0.033601,3.135494,0.426561,0.390827
3,209067,Zinacantepec,Edo. de México,0.693147,2.0,1.0,1.0,4.158883,4.219508,53666.0,...,650000.0,2012.0,3.0,9.0,1,0.107927,0.033601,1.609438,0.426561,0.475439
4,185997,Zapopan,Jalisco,2.397895,2.0,1.0,1.0,4.564348,4.564348,47835.0,...,1150000.0,2016.0,6.0,7.0,1,0.078086,0.000000,0.000000,0.478679,0.390827

In [5]:
featuresTest['precio'] = -1
featuresTest.head()

,id,ciudad,provincia,antiguedad,habitaciones,garages,banos,metroscubiertos,metrostotales,idzona,...,anio,mes,dia,datoBienCargado,peso_IDF_descripcion,peso_IDF_titulo,metrosdescubiertos,tipodepropiedad_cb,caracteristicas_cb,precio
0,4941,Miguel Hidalgo,Distrito Federal,3.401197,3.0,2.132417,4.0,5.707110,1.141805,2.132417,...,2013.0,7.0,20.0,0,0.018539,0.033601,1.141805,0.426768,0.392836,-1
1,51775,Mérida,Yucatán,1.141805,1.0,1.000000,1.0,4.219508,4.219508,113851.000000,...,2015.0,10.0,24.0,1,0.714877,0.000000,0.000000,0.480004,0.392836,-1
2,115253,Coyoacán,Distrito Federal,0.000000,2.0,1.000000,2.0,4.477337,4.615121,23620.000000,...,2015.0,5.0,30.0,1,0.530057,0.638628,2.639057,0.480004,0.470865,-1
3,299321,Acapulco de Juárez,Guerrero,1.098612,2.0,2.000000,2.0,4.465908,4.465908,129347.000000,...,2015.0,4.0,2.0,1,0.296724,0.091081,0.000000,0.480004,0.392836,-1
4,173570,Tultitlán,Edo. de México,2.397895,2.0,1.000000,1.0,4.394449,4.343805,57125.000000,...,2013.0,8.0,15.0,0,0.619535,0.033601,0.000000,0.426768,0.475463,-1

In [6]:
#preparolos dataframes para el one hot encode, para esto los concateno por las dudas que no tengan provincias en comun:

In [7]:
#features Train con la variable encodeada:
col = featuresTrain.columns

In [8]:
featuresTest = featuresTest.loc[:,col]
featuresTrain = featuresTrain.loc[:,col]

In [9]:
featuresTrain.columns

Index(['id', 'ciudad', 'provincia', 'antiguedad', 'habitaciones', 'garages',
       'banos', 'metroscubiertos', 'metrostotales', 'idzona', 'lat', 'lng',
       'precio', 'anio', 'mes', 'dia', 'datoBienCargado',
       'peso_IDF_descripcion', 'peso_IDF_titulo', 'metrosdescubiertos',
       'tipodepropiedad_cb', 'caracteristicas_cb'],
      dtype='object')

In [10]:
featuresTest.columns

Index(['id', 'ciudad', 'provincia', 'antiguedad', 'habitaciones', 'garages',
       'banos', 'metroscubiertos', 'metrostotales', 'idzona', 'lat', 'lng',
       'precio', 'anio', 'mes', 'dia', 'datoBienCargado',
       'peso_IDF_descripcion', 'peso_IDF_titulo', 'metrosdescubiertos',
       'tipodepropiedad_cb', 'caracteristicas_cb'],
      dtype='object')

In [11]:
#concateno los dataframes:
features = pd.concat([featuresTrain,featuresTest],axis=0)

In [12]:
features.shape

(300000, 22)

In [13]:
features.head()

,id,ciudad,provincia,antiguedad,habitaciones,garages,banos,metroscubiertos,metrostotales,idzona,...,precio,anio,mes,dia,datoBienCargado,peso_IDF_descripcion,peso_IDF_titulo,metrosdescubiertos,tipodepropiedad_cb,caracteristicas_cb
0,254099,Benito Juárez,Distrito Federal,2.210044,2.0,1.0,2.0,4.394449,4.394449,23533.0,...,2273000.0,2015.0,8.0,23.0,1,0.086408,0.000000,0.000000,0.478679,0.390827
1,53461,La Magdalena Contreras,Distrito Federal,2.397895,3.0,2.0,2.0,5.594711,5.198497,24514.0,...,3600000.0,2013.0,6.0,28.0,0,0.344349,0.165371,0.000000,0.386072,0.475439
2,247984,Tonalá,Jalisco,1.791759,3.0,2.0,2.0,4.976734,5.117994,48551.0,...,1200000.0,2015.0,10.0,17.0,1,0.992218,0.033601,3.135494,0.426561,0.390827
3,209067,Zinacantepec,Edo. de México,0.693147,2.0,1.0,1.0,4.158883,4.219508,53666.0,...,650000.0,2012.0,3.0,9.0,1,0.107927,0.033601,1.609438,0.426561,0.475439
4,185997,Zapopan,Jalisco,2.397895,2.0,1.0,1.0,4.564348,4.564348,47835.0,...,1150000.0,2016.0,6.0,7.0,1,0.078086,0.000000,0.000000,0.478679,0.390827

In [14]:
one_hot_enc = ce.OneHotEncoder()
one_hot_encoded = one_hot_enc.fit_transform(features[categorias])

In [15]:
features.head()

,id,ciudad,provincia,antiguedad,habitaciones,garages,banos,metroscubiertos,metrostotales,idzona,...,precio,anio,mes,dia,datoBienCargado,peso_IDF_descripcion,peso_IDF_titulo,metrosdescubiertos,tipodepropiedad_cb,caracteristicas_cb
0,254099,Benito Juárez,Distrito Federal,2.210044,2.0,1.0,2.0,4.394449,4.394449,23533.0,...,2273000.0,2015.0,8.0,23.0,1,0.086408,0.000000,0.000000,0.478679,0.390827
1,53461,La Magdalena Contreras,Distrito Federal,2.397895,3.0,2.0,2.0,5.594711,5.198497,24514.0,...,3600000.0,2013.0,6.0,28.0,0,0.344349,0.165371,0.000000,0.386072,0.475439
2,247984,Tonalá,Jalisco,1.791759,3.0,2.0,2.0,4.976734,5.117994,48551.0,...,1200000.0,2015.0,10.0,17.0,1,0.992218,0.033601,3.135494,0.426561,0.390827
3,209067,Zinacantepec,Edo. de México,0.693147,2.0,1.0,1.0,4.158883,4.219508,53666.0,...,650000.0,2012.0,3.0,9.0,1,0.107927,0.033601,1.609438,0.426561,0.475439
4,185997,Zapopan,Jalisco,2.397895,2.0,1.0,1.0,4.564348,4.564348,47835.0,...,1150000.0,2016.0,6.0,7.0,1,0.078086,0.000000,0.000000,0.478679,0.390827

In [16]:
one_hot_encoded.head()

,provincia_1,provincia_2,provincia_3,provincia_4,provincia_5,provincia_6,provincia_7,provincia_8,provincia_9,provincia_10,...,provincia_24,provincia_25,provincia_26,provincia_27,provincia_28,provincia_29,provincia_30,provincia_31,provincia_32,provincia_33
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
features = pd.concat([features,one_hot_encoded],axis=1)

In [18]:
features.shape

(300000, 55)

In [19]:
features.head()

,id,ciudad,provincia,antiguedad,habitaciones,garages,banos,metroscubiertos,metrostotales,idzona,...,provincia_24,provincia_25,provincia_26,provincia_27,provincia_28,provincia_29,provincia_30,provincia_31,provincia_32,provincia_33
0,254099,Benito Juárez,Distrito Federal,2.210044,2.0,1.0,2.0,4.394449,4.394449,23533.0,...,0,0,0,0,0,0,0,0,0,0
1,53461,La Magdalena Contreras,Distrito Federal,2.397895,3.0,2.0,2.0,5.594711,5.198497,24514.0,...,0,0,0,0,0,0,0,0,0,0
2,247984,Tonalá,Jalisco,1.791759,3.0,2.0,2.0,4.976734,5.117994,48551.0,...,0,0,0,0,0,0,0,0,0,0
3,209067,Zinacantepec,Edo. de México,0.693147,2.0,1.0,1.0,4.158883,4.219508,53666.0,...,0,0,0,0,0,0,0,0,0,0
4,185997,Zapopan,Jalisco,2.397895,2.0,1.0,1.0,4.564348,4.564348,47835.0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
featuresTrain = features.loc[features['precio']!=-1]
featuresTest = features.loc[features['precio']==-1].drop('precio',1)

In [21]:
featuresTrain.shape

(240000, 55)

In [22]:
featuresTest.shape

(60000, 54)

In [23]:
featuresTrain.head()

,id,ciudad,provincia,antiguedad,habitaciones,garages,banos,metroscubiertos,metrostotales,idzona,...,provincia_24,provincia_25,provincia_26,provincia_27,provincia_28,provincia_29,provincia_30,provincia_31,provincia_32,provincia_33
0,254099,Benito Juárez,Distrito Federal,2.210044,2.0,1.0,2.0,4.394449,4.394449,23533.0,...,0,0,0,0,0,0,0,0,0,0
1,53461,La Magdalena Contreras,Distrito Federal,2.397895,3.0,2.0,2.0,5.594711,5.198497,24514.0,...,0,0,0,0,0,0,0,0,0,0
2,247984,Tonalá,Jalisco,1.791759,3.0,2.0,2.0,4.976734,5.117994,48551.0,...,0,0,0,0,0,0,0,0,0,0
3,209067,Zinacantepec,Edo. de México,0.693147,2.0,1.0,1.0,4.158883,4.219508,53666.0,...,0,0,0,0,0,0,0,0,0,0
4,185997,Zapopan,Jalisco,2.397895,2.0,1.0,1.0,4.564348,4.564348,47835.0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
featuresTrain.head()

,id,ciudad,provincia,antiguedad,habitaciones,garages,banos,metroscubiertos,metrostotales,idzona,...,provincia_24,provincia_25,provincia_26,provincia_27,provincia_28,provincia_29,provincia_30,provincia_31,provincia_32,provincia_33
0,254099,Benito Juárez,Distrito Federal,2.210044,2.0,1.0,2.0,4.394449,4.394449,23533.0,...,0,0,0,0,0,0,0,0,0,0
1,53461,La Magdalena Contreras,Distrito Federal,2.397895,3.0,2.0,2.0,5.594711,5.198497,24514.0,...,0,0,0,0,0,0,0,0,0,0
2,247984,Tonalá,Jalisco,1.791759,3.0,2.0,2.0,4.976734,5.117994,48551.0,...,0,0,0,0,0,0,0,0,0,0
3,209067,Zinacantepec,Edo. de México,0.693147,2.0,1.0,1.0,4.158883,4.219508,53666.0,...,0,0,0,0,0,0,0,0,0,0
4,185997,Zapopan,Jalisco,2.397895,2.0,1.0,1.0,4.564348,4.564348,47835.0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
# transformo los dataframes en .csv:
featuresTest.to_csv('featuresTest4.csv',index=False)
featuresTrain.to_csv('featuresTrain4.csv',index=False)